import turtle
import time

star = turtle.Turtle()
rays = turtle.Turtle()
text = turtle.Turtle()
suitcase = turtle.Turtle()
suitcase.hideturtle()
star.penup()
wn = turtle.Screen()
rays.penup()
rays.hideturtle()
rays.goto(0, 250)
rays.color('yellow')
rays.fillcolor('lightyellow')
rays.pendown()
rays.begin_fill()
rays.goto(450, -200)
rays.goto(-450, -200)
rays.goto(0, 250)
rays.end_fill()
wn.addshape('pictures/Star.gif')
star.shape('pictures/Star.gif')
star.speed(1)
star.goto(0, 300)
text.hideturtle()
text.penup()
text.goto(-150, -300)
text.write('Hello! And welcome to Heaven!', font=("Verdana", 15, "normal"))
time.sleep(5)
text.clear()
text.write('Welp, this is it.', font=("Verdana", 15, "normal"))
time.sleep(5)
text.clear()
text.write("I'll leave you alone to unpack your things.", font=("Verdana", 15, "normal"))
time.sleep(5)
text.clear()
rays.clear()
star.hideturtle()
suitcase.showturtle()
wn.addshape('pictures/SuitcaseClosed.gif')
suitcase.shape('pictures/SuitcaseClosed.gif')
def suitcaseclicked():
    wn.addshape('pictures/SuitcaseOpen.gif')
    suitcase.shape('pictures/SuitcaseOpen.gif')
    time.sleep(5)
suitcase.onclick()

wn.mainloop()