import turtle
import time

fire = turtle.Turtle()
wn = turtle.Screen()
wn.addshape('pictures/Fire.gif')
fire.shape('pictures/Fire.gif')
trey = turtle.Turtle()
'''
class Death():
    def __init__(self):
        self = self
    
    def heaven():
        star = turtle.Turtle()
        rays = turtle.Turtle()
        text = turtle.Turtle()
        suitcase = turtle.Turtle()
        clicker = turtle.Turtle()
        suitcase.hideturtle()
        star.penup()
        wn = turtle.Screen()
        clicker.hideturtle()
        clicker.penup()
        clicker.goto(1000, 1000)
        text.hideturtle()
        rays.penup()
        rays.hideturtle()
        rays.goto(0, 250)
        rays.color('yellow')
        rays.fillcolor('lightyellow')
        rays.pendown()
        rays.begin_fill()
        rays.goto(450, -200)
        rays.goto(-450, -200)
        rays.goto(0, 250)
        rays.end_fill()
        wn.addshape('pictures/Star.gif')
        star.shape('pictures/Star.gif')
        star.speed(1)
        star.goto(0, 300)
        text.penup()
        text.goto(-150, -300)
        text.write('Hello! And welcome to Heaven!', font=("Verdana", 15, "normal"))
        time.sleep(5)
        text.clear()
        text.write('Welp, this is it.', font=("Verdana", 15, "normal"))
        time.sleep(5)
        text.clear()
        text.write("I'll leave you alone to unpack your things.", font=("Verdana", 15, "normal"))
        time.sleep(5)
        text.clear()
        rays.clear()
        star.hideturtle()
        suitcase.showturtle()
        wn.addshape('pictures/SuitcaseClosed.gif')
        suitcase.shape('pictures/SuitcaseClosed.gif')
        def clickerclicked(x, y):
            wn.addshape('pictures/HeavenEnding.gif')
            clicker.shape('pictures/HeavenEnding.gif')
        def suitcaseclicked(x, y):
            wn.addshape('pictures/SuitcaseOpen.gif')
            suitcase.shape('pictures/SuitcaseOpen.gif')
            time.sleep(5)
            suitcase.hideturtle()
            clicker.goto(0,0)
            clicker.showturtle()
            wn.addshape('pictures/Present.gif')
            clicker.shape('pictures/Present.gif')
            clicker.onclick(clickerclicked)
        suitcase.onclick(suitcaseclicked)
        wn.mainloop()
'''
