import turtle
import time

class Death():
    def __init__(self):
        self = self
    
    def heaven():
        star = turtle.Turtle()
        rays = turtle.Turtle()
        text = turtle.Turtle()
        suitcase = turtle.Turtle()
        clicker = turtle.Turtle()
        suitcase.hideturtle()
        star.penup()
        wn = turtle.Screen()
        clicker.hideturtle()
        clicker.penup()
        clicker.goto(1000, 1000)
        text.hideturtle()
        rays.penup()
        rays.hideturtle()
        rays.goto(0, 250)
        rays.color('yellow')
        rays.fillcolor('lightyellow')
        rays.pendown()
        rays.begin_fill()
        rays.goto(450, -200)
        rays.goto(-450, -200)
        rays.goto(0, 250)
        rays.end_fill()
        wn.addshape('pictures/Star.gif')
        star.shape('pictures/Star.gif')
        star.speed(1)
        star.goto(0, 300)
        text.penup()
        text.goto(-150, -300)
        text.write('Hello! And welcome to Heaven!', font=("Verdana", 15, "normal"))
        time.sleep(5)
        text.clear()
        text.write('Welp, this is it.', font=("Verdana", 15, "normal"))
        time.sleep(5)
        text.clear()
        text.write("I'll leave you alone to unpack your things.", font=("Verdana", 15, "normal"))
        time.sleep(5)
        text.clear()
        rays.clear()
        star.hideturtle()
        suitcase.showturtle()
        wn.addshape('pictures/SuitcaseClosed.gif')
        suitcase.shape('pictures/SuitcaseClosed.gif')
        def clickerclicked(x, y):
            wn.addshape('pictures/HeavenEnding.gif')
            clicker.shape('pictures/HeavenEnding.gif')
        def suitcaseclicked(x, y):
            wn.addshape('pictures/SuitcaseOpen.gif')
            suitcase.shape('pictures/SuitcaseOpen.gif')
            time.sleep(5)
            suitcase.hideturtle()
            clicker.goto(0,0)
            clicker.showturtle()
            wn.addshape('pictures/Present.gif')
            clicker.shape('pictures/Present.gif')
            clicker.onclick(clickerclicked)
        suitcase.onclick(suitcaseclicked)
        wn.mainloop()
    def Hell():
        #creates background
        fire = turtle.Turtle()
        wn = turtle.Screen()
        wn.addshape('pictures/Fire.gif')
        fire.penup()
        fire.shape('pictures/Fire.gif')

        #creates the Devil
        wn.addshape('pictures/Trey1.gif')
        trey = turtle.Turtle()
        trey.penup()
        trey.goto(0, 100)
        trey.shape('pictures/Trey1.gif')

        #creates captions
        text = turtle.Turtle()
        text.hideturtle()
        text.penup()
        text.goto(-225, -300)
        text.color('white')
        text.write(f'How dare you be in my sight!', font=("Times New Roman", 30, "normal"))
        time.sleep(5)
        text.clear()
        text.write(f'You want to know why you are here?', font=("Times New Roman", 30, "normal"))
        time.sleep(5)
        text.clear()
        text.write(f'Well, I think it is pretty obvious...', font=("Times New Roman", 30, "normal"))
        time.sleep(5)
        text.clear()
        text.goto(-325, -300)
        text.write(f'You have angered the "higher power" with your sinister behavior!', font=("Times New Roman", 20, "normal"))
        time.sleep(5)
        text.clear()
        text.goto(-225, -300)
        text.write(f'AND NOW, I GET TO TORTURE YOU!!!', font=("Times New Roman", 30, "normal"))
        time.sleep(2)
        text.clear()
        text.write(f'HA HA HA!!!!', font=("Times New Roman", 30, "normal"))
        for size in range(10):
            realsize = size * 50
            wn.setup(1040 - realsize, 850 - realsize)
            time.sleep(1)
        wn.bye()